name: 'FoundryVTT AutoPublish'
description: 'Publishes a new FoundryVTT module version to the FoundryVTT module administration site.'
inputs:
  username:
    required: true
    description: |
      The username of the account that will be used to access the FoundryVTT
        module administration site.

  password:
    required: true
    description: |
       The source that the password of the account that will be used to access
        the site will be read from.

  module-id:
    required: true
    description: |
      The numeric ID of the module to publish a new version of.

  manifest-url:
    required: true
    description: |
      The manifest URL for the specific module version being published.

  manifest-file:
    required: true
    description: |
      Path of a module manifest file to read information from.

runs:
  using: "composite"
  steps:
    - run: |
        import os, shlex, subprocess
        print(os.environ.keys())
        def run(command, *args, **kwargs):
            subprocess.run([
              part.format(**os.environ) for part in shlex.split(command)
            ], *args, **kwargs)

        run("pip install poetry")
        run(
            "poetry install",
            cwd="${{ github.action_path }}",
        )
        run(
            """
            poetry run fvtt-autopublish
              --username        "{INPUT_USERNAME}"
              --password-source "input"
              --module-id       "{INPUT_MODULE_ID}"
              --manifest-url    "{INPUT_MANIFEST_URL}"
              --manifest-file   "{INPUT_MANIFEST_FILE}"
            """,
            input="{INPUT_PASSWORD}"
        )
      shell: python
      env:
        INPUT_USERNAME: ${{ inputs.username }}
        INPUT_PASSWORD: ${{ inputs.password }}
        INPUT_MODULE_ID: ${{ inputs.module-id }}
        INPUT_MANIFEST_URL: ${{ inputs.manifest-url }}
        INPUT_MANIFEST_FILE: ${{ inputs.manifest-file }}
