name: 'FoundryVTT AutoPublish'
description: 'Publishes a new FoundryVTT module version to the FoundryVTT module administration site.'
branding:
  icon: upload
  color: gray-dark
inputs:
  username:
    required: true
    description: |
      The username of the account that will be used to access the FoundryVTT module administration site.

  password:
    required: true
    description: |
       The password of the account that will be used to access the FoundryVTT module administration site.

  module-id:
    required: true
    description: |
      The numeric ID of the module to publish a new version of.

  manifest-url:
    required: true
    description: |
      The manifest URL for the specific module version being published.

  manifest-file:
    required: true
    description: |
      Path of a module manifest file to read information from.

runs:
  using: "docker"
  image: 'Dockerfile'
  args: [
    "--username",        "{INPUT_USERNAME}",
    "--password-source", "environment:INPUT_PASSWORD",
    "--module-id",       "{INPUT_MODULE_ID}",
    "--manifest-url",    "{INPUT_MANIFEST_URL}",
    "--manifest-file",   "{INPUT_MANIFEST_FILE}",
  ]
  env:
    INPUT_USERNAME: ${{ inputs.username }}
    INPUT_PASSWORD: ${{ inputs.password }}
    INPUT_MODULE_ID: ${{ inputs.module-id }}
    INPUT_MANIFEST_URL: ${{ inputs.manifest-url }}
    INPUT_MANIFEST_FILE: ${{github.workspace}}/${{ inputs.manifest-file }}
