name: 'FoundryVTT AutoPublish'
description: 'Publishes a new FoundryVTT module version to the FoundryVTT module administration site.'
branding:
  icon: upload
  color: gray-dark
inputs:
  username:
    required: true
    description: |
      The username of the account that will be used to access the FoundryVTT module administration site.

  password:
    required: true
    description: |
       The password of the account that will be used to access the FoundryVTT module administration site.

  module-id:
    required: true
    description: |
      The numeric ID of the module to publish a new version of.

  manifest-url:
    required: true
    description: |
      The manifest URL for the specific module version being published.

  manifest-file:
    required: true
    description: |
      Path of a module manifest file to read information from.

runs:
  using: "docker"
  image: 'Dockerfile'
  args: [
    "--username",        "{FVTT_USERNAME}",
    "--password-source", "environment",
    "--module-id",       "{FVTT_MODULE_ID}",
    "--manifest-url",    "{FVTT_MANIFEST_URL}",
    "--manifest-file",   "{FVTT_MANIFEST_FILE}",
  ]
  env:
    FVTT_USERNAME: ${{ inputs.username }}
    FVTT_PASSWORD: ${{ inputs.password }}
    FVTT_MODULE_ID: ${{ inputs.module-id }}
    FVTT_MANIFEST_URL: ${{ inputs.manifest-url }}
    FVTT_MANIFEST_FILE: ${{github.workspace}}/${{ inputs.manifest-file }}
